// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account_events.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Created struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Created) Reset()         { *m = Created{} }
func (m *Created) String() string { return proto.CompactTextString(m) }
func (*Created) ProtoMessage()    {}
func (*Created) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_events_66f1d93b7cf70b37, []int{0}
}
func (m *Created) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Created.Unmarshal(m, b)
}
func (m *Created) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Created.Marshal(b, m, deterministic)
}
func (dst *Created) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Created.Merge(dst, src)
}
func (m *Created) XXX_Size() int {
	return xxx_messageInfo_Created.Size(m)
}
func (m *Created) XXX_DiscardUnknown() {
	xxx_messageInfo_Created.DiscardUnknown(m)
}

var xxx_messageInfo_Created proto.InternalMessageInfo

func (m *Created) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Created) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type EmailActivationRequired struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Code                 int64    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailActivationRequired) Reset()         { *m = EmailActivationRequired{} }
func (m *EmailActivationRequired) String() string { return proto.CompactTextString(m) }
func (*EmailActivationRequired) ProtoMessage()    {}
func (*EmailActivationRequired) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_events_66f1d93b7cf70b37, []int{1}
}
func (m *EmailActivationRequired) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailActivationRequired.Unmarshal(m, b)
}
func (m *EmailActivationRequired) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailActivationRequired.Marshal(b, m, deterministic)
}
func (dst *EmailActivationRequired) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailActivationRequired.Merge(dst, src)
}
func (m *EmailActivationRequired) XXX_Size() int {
	return xxx_messageInfo_EmailActivationRequired.Size(m)
}
func (m *EmailActivationRequired) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailActivationRequired.DiscardUnknown(m)
}

var xxx_messageInfo_EmailActivationRequired proto.InternalMessageInfo

func (m *EmailActivationRequired) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EmailActivationRequired) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailActivationRequired) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type PhoneActivationRequired struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 int64    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneActivationRequired) Reset()         { *m = PhoneActivationRequired{} }
func (m *PhoneActivationRequired) String() string { return proto.CompactTextString(m) }
func (*PhoneActivationRequired) ProtoMessage()    {}
func (*PhoneActivationRequired) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_events_66f1d93b7cf70b37, []int{2}
}
func (m *PhoneActivationRequired) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneActivationRequired.Unmarshal(m, b)
}
func (m *PhoneActivationRequired) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneActivationRequired.Marshal(b, m, deterministic)
}
func (dst *PhoneActivationRequired) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneActivationRequired.Merge(dst, src)
}
func (m *PhoneActivationRequired) XXX_Size() int {
	return xxx_messageInfo_PhoneActivationRequired.Size(m)
}
func (m *PhoneActivationRequired) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneActivationRequired.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneActivationRequired proto.InternalMessageInfo

func (m *PhoneActivationRequired) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PhoneActivationRequired) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PhoneActivationRequired) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type ResetMobilePasswordRequested struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 int64    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetMobilePasswordRequested) Reset()         { *m = ResetMobilePasswordRequested{} }
func (m *ResetMobilePasswordRequested) String() string { return proto.CompactTextString(m) }
func (*ResetMobilePasswordRequested) ProtoMessage()    {}
func (*ResetMobilePasswordRequested) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_events_66f1d93b7cf70b37, []int{3}
}
func (m *ResetMobilePasswordRequested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetMobilePasswordRequested.Unmarshal(m, b)
}
func (m *ResetMobilePasswordRequested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetMobilePasswordRequested.Marshal(b, m, deterministic)
}
func (dst *ResetMobilePasswordRequested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetMobilePasswordRequested.Merge(dst, src)
}
func (m *ResetMobilePasswordRequested) XXX_Size() int {
	return xxx_messageInfo_ResetMobilePasswordRequested.Size(m)
}
func (m *ResetMobilePasswordRequested) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetMobilePasswordRequested.DiscardUnknown(m)
}

var xxx_messageInfo_ResetMobilePasswordRequested proto.InternalMessageInfo

func (m *ResetMobilePasswordRequested) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResetMobilePasswordRequested) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ResetMobilePasswordRequested) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type PasswordUpdated struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordUpdated) Reset()         { *m = PasswordUpdated{} }
func (m *PasswordUpdated) String() string { return proto.CompactTextString(m) }
func (*PasswordUpdated) ProtoMessage()    {}
func (*PasswordUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_events_66f1d93b7cf70b37, []int{4}
}
func (m *PasswordUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordUpdated.Unmarshal(m, b)
}
func (m *PasswordUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordUpdated.Marshal(b, m, deterministic)
}
func (dst *PasswordUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordUpdated.Merge(dst, src)
}
func (m *PasswordUpdated) XXX_Size() int {
	return xxx_messageInfo_PasswordUpdated.Size(m)
}
func (m *PasswordUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordUpdated proto.InternalMessageInfo

func (m *PasswordUpdated) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PasswordUpdated) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type EmailUpdated struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OldEmail             string   `protobuf:"bytes,2,opt,name=old_email,json=oldEmail,proto3" json:"old_email,omitempty"`
	NewEmail             string   `protobuf:"bytes,3,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailUpdated) Reset()         { *m = EmailUpdated{} }
func (m *EmailUpdated) String() string { return proto.CompactTextString(m) }
func (*EmailUpdated) ProtoMessage()    {}
func (*EmailUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_events_66f1d93b7cf70b37, []int{5}
}
func (m *EmailUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailUpdated.Unmarshal(m, b)
}
func (m *EmailUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailUpdated.Marshal(b, m, deterministic)
}
func (dst *EmailUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailUpdated.Merge(dst, src)
}
func (m *EmailUpdated) XXX_Size() int {
	return xxx_messageInfo_EmailUpdated.Size(m)
}
func (m *EmailUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EmailUpdated proto.InternalMessageInfo

func (m *EmailUpdated) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EmailUpdated) GetOldEmail() string {
	if m != nil {
		return m.OldEmail
	}
	return ""
}

func (m *EmailUpdated) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type Activated struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Activated) Reset()         { *m = Activated{} }
func (m *Activated) String() string { return proto.CompactTextString(m) }
func (*Activated) ProtoMessage()    {}
func (*Activated) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_events_66f1d93b7cf70b37, []int{6}
}
func (m *Activated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activated.Unmarshal(m, b)
}
func (m *Activated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activated.Marshal(b, m, deterministic)
}
func (dst *Activated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activated.Merge(dst, src)
}
func (m *Activated) XXX_Size() int {
	return xxx_messageInfo_Activated.Size(m)
}
func (m *Activated) XXX_DiscardUnknown() {
	xxx_messageInfo_Activated.DiscardUnknown(m)
}

var xxx_messageInfo_Activated proto.InternalMessageInfo

func (m *Activated) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Activated) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Deleted struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Deleted) Reset()         { *m = Deleted{} }
func (m *Deleted) String() string { return proto.CompactTextString(m) }
func (*Deleted) ProtoMessage()    {}
func (*Deleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_events_66f1d93b7cf70b37, []int{7}
}
func (m *Deleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deleted.Unmarshal(m, b)
}
func (m *Deleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deleted.Marshal(b, m, deterministic)
}
func (dst *Deleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deleted.Merge(dst, src)
}
func (m *Deleted) XXX_Size() int {
	return xxx_messageInfo_Deleted.Size(m)
}
func (m *Deleted) XXX_DiscardUnknown() {
	xxx_messageInfo_Deleted.DiscardUnknown(m)
}

var xxx_messageInfo_Deleted proto.InternalMessageInfo

func (m *Deleted) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Deleted) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*Created)(nil), "account.Created")
	proto.RegisterType((*EmailActivationRequired)(nil), "account.EmailActivationRequired")
	proto.RegisterType((*PhoneActivationRequired)(nil), "account.PhoneActivationRequired")
	proto.RegisterType((*ResetMobilePasswordRequested)(nil), "account.ResetMobilePasswordRequested")
	proto.RegisterType((*PasswordUpdated)(nil), "account.PasswordUpdated")
	proto.RegisterType((*EmailUpdated)(nil), "account.EmailUpdated")
	proto.RegisterType((*Activated)(nil), "account.Activated")
	proto.RegisterType((*Deleted)(nil), "account.Deleted")
}

func init() {
	proto.RegisterFile("account_events.proto", fileDescriptor_account_events_66f1d93b7cf70b37)
}

var fileDescriptor_account_events_66f1d93b7cf70b37 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x69, 0xab, 0x76, 0xfd, 0x10, 0x85, 0x30, 0xb0, 0xa8, 0x87, 0xd1, 0xd3, 0x4e, 0x5e,
	0x64, 0x78, 0xf2, 0x20, 0xea, 0x51, 0x18, 0x15, 0x61, 0xb7, 0x91, 0x35, 0x1f, 0x18, 0xc8, 0xf2,
	0xd5, 0x24, 0x5d, 0xff, 0x7d, 0x49, 0x96, 0x89, 0x87, 0x0a, 0x96, 0xdd, 0xf2, 0xf2, 0xde, 0xfb,
	0x11, 0x1e, 0x81, 0x29, 0x6f, 0x1a, 0xea, 0xb4, 0x5b, 0xe3, 0x0e, 0xb5, 0xb3, 0x77, 0xad, 0x21,
	0x47, 0x2c, 0x8f, 0xb7, 0xd5, 0x02, 0xf2, 0x67, 0x83, 0xdc, 0xa1, 0x60, 0x17, 0x90, 0x4a, 0x51,
	0x26, 0xb3, 0x64, 0x9e, 0xd5, 0xa9, 0x14, 0xec, 0x1a, 0x26, 0x9d, 0x45, 0xa3, 0xf9, 0x16, 0xcb,
	0x74, 0x96, 0xcc, 0x8b, 0xfa, 0x47, 0x57, 0xef, 0x70, 0xf5, 0xba, 0xe5, 0x52, 0x3d, 0x35, 0x4e,
	0xee, 0xb8, 0x93, 0xa4, 0x6b, 0xfc, 0xea, 0xa4, 0x19, 0xc0, 0x4c, 0xe1, 0x14, 0x7d, 0x34, 0x32,
	0xf6, 0x82, 0x31, 0x38, 0x69, 0x48, 0x60, 0x99, 0x85, 0x5c, 0x38, 0x7b, 0xe8, 0xf2, 0x93, 0x34,
	0xfe, 0x0f, 0xda, 0xfa, 0xe8, 0x01, 0x1a, 0xc4, 0x20, 0x74, 0x05, 0xb7, 0x35, 0x5a, 0x74, 0x6f,
	0xb4, 0x91, 0x0a, 0x97, 0xdc, 0xda, 0x9e, 0x8c, 0xf0, 0x60, 0xb4, 0xee, 0x28, 0xf2, 0x23, 0x5c,
	0x1e, 0x70, 0x1f, 0xad, 0x18, 0x3d, 0xe1, 0x0a, 0xce, 0xc3, 0x84, 0x7f, 0x75, 0x6f, 0xa0, 0x20,
	0x25, 0xd6, 0xbf, 0xb7, 0x9b, 0x90, 0x12, 0xa1, 0xe3, 0x4d, 0x8d, 0x7d, 0x34, 0xb3, 0xbd, 0xa9,
	0xb1, 0x0f, 0x66, 0xf5, 0x00, 0x45, 0x9c, 0x70, 0xe4, 0x93, 0x16, 0x90, 0xbf, 0xa0, 0xc2, 0x91,
	0xb5, 0xcd, 0x59, 0xf8, 0x53, 0xf7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x66, 0xe5, 0xa5, 0xf8,
	0x6b, 0x02, 0x00, 0x00,
}
