// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sender int32

const (
	Sender_ACTIVATION Sender = 0
	Sender_RESET      Sender = 1
)

var Sender_name = map[int32]string{
	0: "ACTIVATION",
	1: "RESET",
}
var Sender_value = map[string]int32{
	"ACTIVATION": 0,
	"RESET":      1,
}

func (x Sender) String() string {
	return proto.EnumName(Sender_name, int32(x))
}
func (Sender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{0}
}

type RegisterEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenName            string   `protobuf:"bytes,4,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	Locale               string   `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterEmailRequest) Reset()         { *m = RegisterEmailRequest{} }
func (m *RegisterEmailRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterEmailRequest) ProtoMessage()    {}
func (*RegisterEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{0}
}
func (m *RegisterEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterEmailRequest.Unmarshal(m, b)
}
func (m *RegisterEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterEmailRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterEmailRequest.Merge(dst, src)
}
func (m *RegisterEmailRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterEmailRequest.Size(m)
}
func (m *RegisterEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterEmailRequest proto.InternalMessageInfo

func (m *RegisterEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterEmailRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterEmailRequest) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *RegisterEmailRequest) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *RegisterEmailRequest) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

type RegisterMobileRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	MobileId             string   `protobuf:"bytes,2,opt,name=mobile_id,json=mobileId,proto3" json:"mobile_id,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FamilyName           string   `protobuf:"bytes,4,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenName            string   `protobuf:"bytes,5,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	Locale               string   `protobuf:"bytes,6,opt,name=locale,proto3" json:"locale,omitempty"`
	Company              string   `protobuf:"bytes,7,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterMobileRequest) Reset()         { *m = RegisterMobileRequest{} }
func (m *RegisterMobileRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterMobileRequest) ProtoMessage()    {}
func (*RegisterMobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{1}
}
func (m *RegisterMobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterMobileRequest.Unmarshal(m, b)
}
func (m *RegisterMobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterMobileRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterMobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterMobileRequest.Merge(dst, src)
}
func (m *RegisterMobileRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterMobileRequest.Size(m)
}
func (m *RegisterMobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterMobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterMobileRequest proto.InternalMessageInfo

func (m *RegisterMobileRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterMobileRequest) GetMobileId() string {
	if m != nil {
		return m.MobileId
	}
	return ""
}

func (m *RegisterMobileRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterMobileRequest) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *RegisterMobileRequest) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *RegisterMobileRequest) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *RegisterMobileRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type Account struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	FamilyName           string   `protobuf:"bytes,4,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenName            string   `protobuf:"bytes,5,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	Locale               string   `protobuf:"bytes,6,opt,name=locale,proto3" json:"locale,omitempty"`
	Company              string   `protobuf:"bytes,7,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{2}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Account) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *Account) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *Account) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *Account) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type AddMobileRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	MobileId             string   `protobuf:"bytes,2,opt,name=mobile_id,json=mobileId,proto3" json:"mobile_id,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMobileRequest) Reset()         { *m = AddMobileRequest{} }
func (m *AddMobileRequest) String() string { return proto.CompactTextString(m) }
func (*AddMobileRequest) ProtoMessage()    {}
func (*AddMobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{3}
}
func (m *AddMobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMobileRequest.Unmarshal(m, b)
}
func (m *AddMobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMobileRequest.Marshal(b, m, deterministic)
}
func (dst *AddMobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMobileRequest.Merge(dst, src)
}
func (m *AddMobileRequest) XXX_Size() int {
	return xxx_messageInfo_AddMobileRequest.Size(m)
}
func (m *AddMobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMobileRequest proto.InternalMessageInfo

func (m *AddMobileRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AddMobileRequest) GetMobileId() string {
	if m != nil {
		return m.MobileId
	}
	return ""
}

func (m *AddMobileRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ActivateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Code                 int64    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateRequest) Reset()         { *m = ActivateRequest{} }
func (m *ActivateRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateRequest) ProtoMessage()    {}
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{4}
}
func (m *ActivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateRequest.Unmarshal(m, b)
}
func (m *ActivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateRequest.Marshal(b, m, deterministic)
}
func (dst *ActivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateRequest.Merge(dst, src)
}
func (m *ActivateRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateRequest.Size(m)
}
func (m *ActivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateRequest proto.InternalMessageInfo

func (m *ActivateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ActivateRequest) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type RetrieveRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveRequest) Reset()         { *m = RetrieveRequest{} }
func (m *RetrieveRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveRequest) ProtoMessage()    {}
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{5}
}
func (m *RetrieveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveRequest.Unmarshal(m, b)
}
func (m *RetrieveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveRequest.Marshal(b, m, deterministic)
}
func (dst *RetrieveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveRequest.Merge(dst, src)
}
func (m *RetrieveRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveRequest.Size(m)
}
func (m *RetrieveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveRequest proto.InternalMessageInfo

func (m *RetrieveRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SearchRequest struct {
	Search               string   `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{6}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (dst *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(dst, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type UpdateRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenName            string   `protobuf:"bytes,4,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	Locale               string   `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	Company              string   `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{7}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *UpdateRequest) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *UpdateRequest) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *UpdateRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type UpdateEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmailRequest) Reset()         { *m = UpdateEmailRequest{} }
func (m *UpdateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailRequest) ProtoMessage()    {}
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{8}
}
func (m *UpdateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailRequest.Unmarshal(m, b)
}
func (m *UpdateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailRequest.Merge(dst, src)
}
func (m *UpdateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailRequest.Size(m)
}
func (m *UpdateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailRequest proto.InternalMessageInfo

func (m *UpdateEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateEmailRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdatePasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{9}
}
func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(dst, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *UpdatePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type InitResetMobilePasswordRequest struct {
	MobileId             string   `protobuf:"bytes,1,opt,name=mobile_id,json=mobileId,proto3" json:"mobile_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResetMobilePasswordRequest) Reset()         { *m = InitResetMobilePasswordRequest{} }
func (m *InitResetMobilePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*InitResetMobilePasswordRequest) ProtoMessage()    {}
func (*InitResetMobilePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{10}
}
func (m *InitResetMobilePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResetMobilePasswordRequest.Unmarshal(m, b)
}
func (m *InitResetMobilePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResetMobilePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *InitResetMobilePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResetMobilePasswordRequest.Merge(dst, src)
}
func (m *InitResetMobilePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_InitResetMobilePasswordRequest.Size(m)
}
func (m *InitResetMobilePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResetMobilePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitResetMobilePasswordRequest proto.InternalMessageInfo

func (m *InitResetMobilePasswordRequest) GetMobileId() string {
	if m != nil {
		return m.MobileId
	}
	return ""
}

type ResetPasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code                 int64    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{11}
}
func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(dst, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResetPasswordRequest) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type DeleteRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{12}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResendCodeRequest struct {
	MobileId             string   `protobuf:"bytes,1,opt,name=mobile_id,json=mobileId,proto3" json:"mobile_id,omitempty"`
	Sender               Sender   `protobuf:"varint,2,opt,name=sender,proto3,enum=account.Sender" json:"sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendCodeRequest) Reset()         { *m = ResendCodeRequest{} }
func (m *ResendCodeRequest) String() string { return proto.CompactTextString(m) }
func (*ResendCodeRequest) ProtoMessage()    {}
func (*ResendCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{13}
}
func (m *ResendCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendCodeRequest.Unmarshal(m, b)
}
func (m *ResendCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendCodeRequest.Marshal(b, m, deterministic)
}
func (dst *ResendCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendCodeRequest.Merge(dst, src)
}
func (m *ResendCodeRequest) XXX_Size() int {
	return xxx_messageInfo_ResendCodeRequest.Size(m)
}
func (m *ResendCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResendCodeRequest proto.InternalMessageInfo

func (m *ResendCodeRequest) GetMobileId() string {
	if m != nil {
		return m.MobileId
	}
	return ""
}

func (m *ResendCodeRequest) GetSender() Sender {
	if m != nil {
		return m.Sender
	}
	return Sender_ACTIVATION
}

type VerifyOldPasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyOldPasswordRequest) Reset()         { *m = VerifyOldPasswordRequest{} }
func (m *VerifyOldPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyOldPasswordRequest) ProtoMessage()    {}
func (*VerifyOldPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_4b25a4461b99e0e6, []int{14}
}
func (m *VerifyOldPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOldPasswordRequest.Unmarshal(m, b)
}
func (m *VerifyOldPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOldPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyOldPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOldPasswordRequest.Merge(dst, src)
}
func (m *VerifyOldPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyOldPasswordRequest.Size(m)
}
func (m *VerifyOldPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOldPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOldPasswordRequest proto.InternalMessageInfo

func (m *VerifyOldPasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterEmailRequest)(nil), "account.RegisterEmailRequest")
	proto.RegisterType((*RegisterMobileRequest)(nil), "account.RegisterMobileRequest")
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*AddMobileRequest)(nil), "account.AddMobileRequest")
	proto.RegisterType((*ActivateRequest)(nil), "account.ActivateRequest")
	proto.RegisterType((*RetrieveRequest)(nil), "account.RetrieveRequest")
	proto.RegisterType((*SearchRequest)(nil), "account.SearchRequest")
	proto.RegisterType((*UpdateRequest)(nil), "account.UpdateRequest")
	proto.RegisterType((*UpdateEmailRequest)(nil), "account.UpdateEmailRequest")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "account.UpdatePasswordRequest")
	proto.RegisterType((*InitResetMobilePasswordRequest)(nil), "account.InitResetMobilePasswordRequest")
	proto.RegisterType((*ResetPasswordRequest)(nil), "account.ResetPasswordRequest")
	proto.RegisterType((*DeleteRequest)(nil), "account.DeleteRequest")
	proto.RegisterType((*ResendCodeRequest)(nil), "account.ResendCodeRequest")
	proto.RegisterType((*VerifyOldPasswordRequest)(nil), "account.VerifyOldPasswordRequest")
	proto.RegisterEnum("account.Sender", Sender_name, Sender_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	RegisterEmail(ctx context.Context, in *RegisterEmailRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RegisterMobile(ctx context.Context, in *RegisterMobileRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AddMobile(ctx context.Context, in *AddMobileRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*Account, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (Accounts_SearchClient, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	VerifyOldPassword(ctx context.Context, in *VerifyOldPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	InitResetMobilePassword(ctx context.Context, in *InitResetMobilePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ResendCode(ctx context.Context, in *ResendCodeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) RegisterEmail(ctx context.Context, in *RegisterEmailRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/RegisterEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) RegisterMobile(ctx context.Context, in *RegisterMobileRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/RegisterMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) AddMobile(ctx context.Context, in *AddMobileRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/AddMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/Activate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.Accounts/Retrieve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (Accounts_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Accounts_serviceDesc.Streams[0], "/account.Accounts/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountsSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Accounts_SearchClient interface {
	Recv() (*Account, error)
	grpc.ClientStream
}

type accountsSearchClient struct {
	grpc.ClientStream
}

func (x *accountsSearchClient) Recv() (*Account, error) {
	m := new(Account)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *accountsClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/UpdateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) VerifyOldPassword(ctx context.Context, in *VerifyOldPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/VerifyOldPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) InitResetMobilePassword(ctx context.Context, in *InitResetMobilePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/InitResetMobilePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) ResendCode(ctx context.Context, in *ResendCodeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Accounts/ResendCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	RegisterEmail(context.Context, *RegisterEmailRequest) (*empty.Empty, error)
	RegisterMobile(context.Context, *RegisterMobileRequest) (*empty.Empty, error)
	AddMobile(context.Context, *AddMobileRequest) (*empty.Empty, error)
	Activate(context.Context, *ActivateRequest) (*empty.Empty, error)
	Retrieve(context.Context, *RetrieveRequest) (*Account, error)
	Search(*SearchRequest, Accounts_SearchServer) error
	Update(context.Context, *UpdateRequest) (*empty.Empty, error)
	UpdateEmail(context.Context, *UpdateEmailRequest) (*empty.Empty, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*empty.Empty, error)
	VerifyOldPassword(context.Context, *VerifyOldPasswordRequest) (*empty.Empty, error)
	InitResetMobilePassword(context.Context, *InitResetMobilePasswordRequest) (*empty.Empty, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*empty.Empty, error)
	Delete(context.Context, *DeleteRequest) (*empty.Empty, error)
	ResendCode(context.Context, *ResendCodeRequest) (*empty.Empty, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_RegisterEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).RegisterEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/RegisterEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).RegisterEmail(ctx, req.(*RegisterEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_RegisterMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMobileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).RegisterMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/RegisterMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).RegisterMobile(ctx, req.(*RegisterMobileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_AddMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMobileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).AddMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/AddMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).AddMobile(ctx, req.(*AddMobileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/Activate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Activate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountsServer).Search(m, &accountsSearchServer{stream})
}

type Accounts_SearchServer interface {
	Send(*Account) error
	grpc.ServerStream
}

type accountsSearchServer struct {
	grpc.ServerStream
}

func (x *accountsSearchServer) Send(m *Account) error {
	return x.ServerStream.SendMsg(m)
}

func _Accounts_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_UpdateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).UpdateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/UpdateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).UpdateEmail(ctx, req.(*UpdateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_VerifyOldPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOldPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).VerifyOldPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/VerifyOldPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).VerifyOldPassword(ctx, req.(*VerifyOldPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_InitResetMobilePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitResetMobilePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).InitResetMobilePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/InitResetMobilePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).InitResetMobilePassword(ctx, req.(*InitResetMobilePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_ResendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).ResendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Accounts/ResendCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).ResendCode(ctx, req.(*ResendCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterEmail",
			Handler:    _Accounts_RegisterEmail_Handler,
		},
		{
			MethodName: "RegisterMobile",
			Handler:    _Accounts_RegisterMobile_Handler,
		},
		{
			MethodName: "AddMobile",
			Handler:    _Accounts_AddMobile_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _Accounts_Activate_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _Accounts_Retrieve_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Accounts_Update_Handler,
		},
		{
			MethodName: "UpdateEmail",
			Handler:    _Accounts_UpdateEmail_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _Accounts_UpdatePassword_Handler,
		},
		{
			MethodName: "VerifyOldPassword",
			Handler:    _Accounts_VerifyOldPassword_Handler,
		},
		{
			MethodName: "InitResetMobilePassword",
			Handler:    _Accounts_InitResetMobilePassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _Accounts_ResetPassword_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Accounts_Delete_Handler,
		},
		{
			MethodName: "ResendCode",
			Handler:    _Accounts_ResendCode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _Accounts_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_4b25a4461b99e0e6) }

var fileDescriptor_account_4b25a4461b99e0e6 = []byte{
	// 763 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0x51, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x71, 0xd2, 0x38, 0xc9, 0x84, 0xa4, 0xe9, 0xaa, 0x0d, 0x26, 0x55, 0x0b, 0x35, 0x0f,
	0x45, 0x20, 0xa5, 0xa8, 0x20, 0xd4, 0x07, 0x8a, 0x08, 0x25, 0x15, 0x79, 0xa0, 0x45, 0x6e, 0xa9,
	0x04, 0x12, 0x8a, 0x9c, 0x78, 0x9a, 0x5a, 0x72, 0xbc, 0xc1, 0x76, 0x5a, 0xe5, 0x18, 0xdc, 0x80,
	0x5b, 0xf0, 0xca, 0x31, 0x38, 0x0e, 0xf2, 0xae, 0xed, 0xec, 0x3a, 0x75, 0xa8, 0x84, 0xca, 0x9b,
	0x67, 0x67, 0xe7, 0xdf, 0x19, 0xcf, 0xec, 0xb7, 0x50, 0x35, 0x07, 0x03, 0x3a, 0x71, 0x83, 0xd6,
	0xd8, 0xa3, 0x01, 0x25, 0xc5, 0xc8, 0x6c, 0xae, 0x0f, 0x29, 0x1d, 0x3a, 0xb8, 0xc3, 0x96, 0xfb,
	0x93, 0xf3, 0x1d, 0x1c, 0x8d, 0x83, 0x29, 0xdf, 0xa5, 0xff, 0x50, 0x60, 0xd5, 0xc0, 0xa1, 0xed,
	0x07, 0xe8, 0x75, 0x46, 0xa6, 0xed, 0x18, 0xf8, 0x6d, 0x82, 0x7e, 0x40, 0x56, 0xa1, 0x80, 0xa1,
	0xad, 0x29, 0x0f, 0x95, 0xc7, 0x65, 0x83, 0x1b, 0xa4, 0x09, 0xa5, 0xb1, 0xe9, 0xfb, 0x57, 0xd4,
	0xb3, 0xb4, 0x1c, 0x73, 0x24, 0x36, 0x79, 0x00, 0x95, 0x73, 0x73, 0x64, 0x3b, 0xd3, 0x9e, 0x6b,
	0x8e, 0x50, 0xcb, 0x33, 0x37, 0xf0, 0xa5, 0x23, 0x73, 0x84, 0x64, 0x03, 0x60, 0x68, 0x5f, 0xa2,
	0xcb, 0xfd, 0x4b, 0xcc, 0x5f, 0x66, 0x2b, 0xcc, 0xdd, 0x00, 0xd5, 0xa1, 0x03, 0xd3, 0x41, 0xad,
	0xc0, 0x5c, 0x91, 0xa5, 0xff, 0x56, 0x60, 0x2d, 0x4e, 0xf1, 0x03, 0xed, 0xdb, 0x0e, 0x0a, 0x39,
	0x8e, 0x2f, 0xa8, 0x8b, 0x71, 0x8e, 0xcc, 0x20, 0xeb, 0x50, 0x1e, 0xb1, 0x6d, 0x3d, 0x3b, 0x49,
	0x92, 0x2f, 0x74, 0x2d, 0xa9, 0x80, 0xfc, 0xe2, 0x02, 0x96, 0xfe, 0x52, 0x40, 0x21, 0xbb, 0x00,
	0x55, 0x2c, 0x80, 0x68, 0x50, 0x1c, 0xd0, 0xd1, 0xd8, 0x74, 0xa7, 0x5a, 0x91, 0x39, 0x62, 0x53,
	0xff, 0xa9, 0x40, 0xb1, 0xcd, 0xdb, 0x44, 0x6a, 0x90, 0xb3, 0x2d, 0x56, 0x49, 0xde, 0xc8, 0xd9,
	0xd6, 0xac, 0x01, 0x39, 0xb1, 0x01, 0x49, 0xc9, 0x79, 0xb1, 0xe4, 0xff, 0x9f, 0xb9, 0x09, 0xf5,
	0xb6, 0x65, 0xdd, 0x66, 0x3b, 0xf4, 0x36, 0x2c, 0xb7, 0x07, 0x81, 0x7d, 0x69, 0x06, 0xc9, 0x09,
	0x4d, 0x28, 0x4d, 0x7c, 0xf4, 0x58, 0x11, 0xfc, 0x90, 0xc4, 0x26, 0x04, 0x96, 0x06, 0xd4, 0x42,
	0x76, 0x44, 0xde, 0x60, 0xdf, 0xfa, 0x16, 0x2c, 0x1b, 0x18, 0x78, 0x36, 0x5e, 0x26, 0x12, 0xa9,
	0xdf, 0xac, 0x6f, 0x43, 0xf5, 0x04, 0x4d, 0x6f, 0x70, 0x11, 0x6f, 0x68, 0x80, 0xea, 0xb3, 0x85,
	0xe8, 0x84, 0xc8, 0xd2, 0xbf, 0x2b, 0x50, 0xfd, 0x34, 0xb6, 0x84, 0x6c, 0xd2, 0x1d, 0xbb, 0xa5,
	0x0b, 0x20, 0x76, 0x41, 0x95, 0xbb, 0x70, 0x08, 0x84, 0xa7, 0xf4, 0x6f, 0x57, 0x57, 0xff, 0x0a,
	0x6b, 0x5c, 0xe7, 0x63, 0xb4, 0x12, 0x4b, 0x6d, 0xc1, 0x5d, 0xea, 0x58, 0xbd, 0x24, 0x90, 0x2b,
	0x56, 0xa8, 0x63, 0xc5, 0x3b, 0xc3, 0x2d, 0x2e, 0x5e, 0xf5, 0x52, 0xda, 0x15, 0x17, 0xaf, 0xe2,
	0x2d, 0xfa, 0x3e, 0x6c, 0x76, 0x5d, 0x3b, 0x30, 0xd0, 0xc7, 0x80, 0x8f, 0x4c, 0xfa, 0x1c, 0x69,
	0x48, 0x14, 0x79, 0x48, 0xf4, 0x7e, 0x88, 0x28, 0x1f, 0x83, 0x74, 0xd0, 0xa2, 0x69, 0x58, 0x04,
	0xaa, 0x78, 0x52, 0xf2, 0xc2, 0xa4, 0x3c, 0x85, 0xea, 0x3b, 0x74, 0x50, 0x1a, 0xb5, 0x54, 0xd5,
	0xb3, 0xdf, 0xf5, 0x19, 0x56, 0xc2, 0x84, 0x5c, 0xeb, 0x80, 0x5a, 0x78, 0x93, 0x12, 0xc8, 0x76,
	0x38, 0x54, 0xae, 0x85, 0x1e, 0x4b, 0xa6, 0xb6, 0xbb, 0xdc, 0x8a, 0x61, 0x7d, 0xc2, 0x96, 0x8d,
	0xc8, 0xad, 0xef, 0x83, 0x76, 0x86, 0x9e, 0x7d, 0x3e, 0x3d, 0x9e, 0xfd, 0xe2, 0x9b, 0x37, 0xe3,
	0xc9, 0x23, 0x50, 0xb9, 0x20, 0xa9, 0x01, 0xb4, 0x0f, 0x4e, 0xbb, 0x67, 0xed, 0xd3, 0xee, 0xf1,
	0x51, 0xfd, 0x0e, 0x29, 0x43, 0xc1, 0xe8, 0x9c, 0x74, 0x4e, 0xeb, 0xca, 0xee, 0xaf, 0x22, 0x94,
	0x22, 0xea, 0xf8, 0xe4, 0x10, 0xaa, 0x12, 0xff, 0xc9, 0x46, 0x92, 0xda, 0x75, 0xef, 0x42, 0xb3,
	0xd1, 0xe2, 0xcf, 0x49, 0x2b, 0x7e, 0x4e, 0x5a, 0x9d, 0xf0, 0x39, 0x21, 0xef, 0xa1, 0x26, 0x43,
	0x9a, 0x6c, 0xce, 0x09, 0x49, 0xb8, 0xc8, 0x54, 0x7a, 0x0d, 0xe5, 0x04, 0x2d, 0xe4, 0x7e, 0x22,
	0x92, 0xc6, 0x4d, 0x66, 0xfc, 0xab, 0xb0, 0x3a, 0xce, 0x0d, 0xa2, 0xcd, 0xc2, 0x65, 0x94, 0x64,
	0x46, 0xbf, 0x84, 0x52, 0x8c, 0x0c, 0x21, 0x3a, 0x45, 0x91, 0x66, 0x5d, 0xd0, 0xe5, 0xf8, 0x7e,
	0x11, 0xfe, 0xf9, 0x10, 0x14, 0xa4, 0x21, 0xf4, 0x56, 0x00, 0xcb, 0x7c, 0xcc, 0x33, 0x85, 0xec,
	0x81, 0xca, 0x2f, 0x9e, 0x10, 0x25, 0x41, 0x26, 0x33, 0xcf, 0xb7, 0x50, 0x11, 0xae, 0x3e, 0x59,
	0x4f, 0x85, 0xdf, 0xb4, 0x67, 0xf2, 0xb5, 0x17, 0x7a, 0x76, 0x2d, 0x0f, 0x32, 0x95, 0x8e, 0x60,
	0x65, 0x6e, 0x6c, 0xc9, 0x56, 0x22, 0x96, 0x35, 0xd2, 0x99, 0x7a, 0x5f, 0xe0, 0x5e, 0x06, 0x31,
	0xc8, 0x76, 0xa2, 0xba, 0x98, 0x29, 0x99, 0xda, 0x6c, 0xe2, 0x05, 0x9c, 0x48, 0x13, 0x3f, 0x8f,
	0x99, 0x4c, 0x9d, 0x3d, 0x50, 0x39, 0x32, 0x84, 0xde, 0x49, 0x0c, 0xc9, 0x8c, 0x7c, 0x03, 0x30,
	0xe3, 0x07, 0x69, 0x4a, 0xc7, 0x4b, 0x50, 0xc9, 0x52, 0xe8, 0xab, 0xcc, 0x7e, 0xfe, 0x27, 0x00,
	0x00, 0xff, 0xff, 0xe0, 0xd4, 0x26, 0x2f, 0xf4, 0x09, 0x00, 0x00,
}
